FROM golang:1.25.3-alpine3.21 AS builder

RUN apk update && apk add ca-certificates
ARG TARGETARCH
ENV CGO_ENABLED=0 GOOS=linux
WORKDIR /app

COPY . .

RUN GOARCH=${TARGETARCH} go build -o server

FROM alpine:3.18

RUN apk update && apk add ca-certificates curl openssl
WORKDIR /app
COPY --from=builder /app/server .

# COPY ca-cert.pem /tmp/ca-cert.pem
# COPY cert.pem /tmp/cert.pem
# COPY key.pem /tmp/key.pem

CMD ["/app/server"]
